// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    gatewayEvents,
    gateways,
    inverterMembers,
    inverterSnapshots,
    inverters,
    inverterInvites,
  ];
  late final Shape0 gatewayEvents = Shape0(
    source: i0.VersionedTable(
      entityName: 'gateway_events',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 gateways = Shape1(
    source: i0.VersionedTable(
      entityName: 'gateways',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_9,
        _column_10,
        _column_2,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 inverterMembers = Shape2(
    source: i0.VersionedTable(
      entityName: 'inverter_members',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(inverter_id, user_id)'],
      columns: [_column_2, _column_17, _column_18, _column_19, _column_15],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 inverterSnapshots = Shape3(
    source: i0.VersionedTable(
      entityName: 'inverter_snapshots',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_2,
        _column_1,
        _column_7,
        _column_8,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 inverters = Shape4(
    source: i0.VersionedTable(
      entityName: 'inverters',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_9,
        _column_38,
        _column_39,
        _column_15,
        _column_40,
        _column_41,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 inverterInvites = Shape5(
    source: i0.VersionedTable(
      entityName: 'inverter_invites',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_9, _column_42, _column_15, _column_43, _column_44],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get gatewayId =>
      columnsByName['gateway_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get inverterId =>
      columnsByName['inverter_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get level =>
      columnsByName['level']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get code =>
      columnsByName['code']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get message =>
      columnsByName['message']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get metadata =>
      columnsByName['metadata']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get recordedAt =>
      columnsByName['recorded_at']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get ingestedAt =>
      columnsByName['ingested_at']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'gateway_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'inverter_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'level',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'code',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'message',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'metadata',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_7(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'recorded_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_8(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'ingested_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get hardwareId =>
      columnsByName['hardware_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get inverterId =>
      columnsByName['inverter_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get provisionedBy =>
      columnsByName['provisioned_by']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get lastSeenAt =>
      columnsByName['last_seen_at']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get firmwareVersion =>
      columnsByName['firmware_version']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get retiredAt =>
      columnsByName['retired_at']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'hardware_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'provisioned_by',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_13(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'last_seen_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'firmware_version',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_15(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_16(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'retired_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get inverterId =>
      columnsByName['inverter_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get role =>
      columnsByName['role']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get email =>
      columnsByName['email']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'user_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'role',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'email',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get inverterId =>
      columnsByName['inverter_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get gatewayId =>
      columnsByName['gateway_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get recordedAt =>
      columnsByName['recorded_at']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get ingestedAt =>
      columnsByName['ingested_at']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get batteryStateOfCharge =>
      columnsByName['battery_state_of_charge']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get batteryVoltage =>
      columnsByName['battery_voltage']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get batteryCurrent =>
      columnsByName['battery_current']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get chargePower =>
      columnsByName['charge_power']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get dischargePower =>
      columnsByName['discharge_power']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get chargeEnergyToday =>
      columnsByName['charge_energy_today']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get dischargeEnergyToday =>
      columnsByName['discharge_energy_today']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get gridImportPower =>
      columnsByName['grid_import_power']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get gridFrequency =>
      columnsByName['grid_frequency']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get gridVoltage =>
      columnsByName['grid_voltage']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get gridCurrent =>
      columnsByName['grid_current']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get gridExportPower =>
      columnsByName['grid_export_power']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get gridExportEnergyToday =>
      columnsByName['grid_export_energy_today']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get gridImportEnergyToday =>
      columnsByName['grid_import_energy_today']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get gridChargePower =>
      columnsByName['grid_charge_power']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get solarEnergyToday =>
      columnsByName['solar_energy_today']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get solarPower =>
      columnsByName['solar_power']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get homeLoadPower =>
      columnsByName['home_load_power']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<double> _column_20(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'battery_state_of_charge',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_21(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'battery_voltage',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_22(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'battery_current',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_23(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'charge_power',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_24(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'discharge_power',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_25(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'charge_energy_today',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_26(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'discharge_energy_today',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_27(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'grid_import_power',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_28(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'grid_frequency',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_29(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'grid_voltage',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_30(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'grid_current',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_31(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'grid_export_power',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_32(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'grid_export_energy_today',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_33(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'grid_import_energy_today',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_34(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'grid_charge_power',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_35(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'solar_energy_today',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_36(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'solar_power',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_37(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'home_load_power',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get inverterSn =>
      columnsByName['inverter_sn']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get displayName =>
      columnsByName['display_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get lastSeenAt =>
      columnsByName['last_seen_at']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get location =>
      columnsByName['location']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_38(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'inverter_sn',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_39(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'display_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_40(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'last_seen_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'location',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get token =>
      columnsByName['token']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get expiresAt =>
      columnsByName['expires_at']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get acceptedAt =>
      columnsByName['accepted_at']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'token',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_43(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'expires_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_44(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'accepted_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2),
);
