// ignore: unused_import
import 'package:flutter/foundation.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'inverter_snapshot.freezed.dart';
part 'inverter_snapshot.g.dart';

@freezed
abstract class InverterSnapshot with _$InverterSnapshot {
  const factory InverterSnapshot({
    required int id,
    @JsonKey(name: 'inverter_id') required String inverterId,
    @JsonKey(name: 'gateway_id') required String gatewayId,
    @JsonKey(name: 'recorded_at')
    /// The timestamp when the snapshot was recorded by the gateway.
    required DateTime recordedAt,
    @JsonKey(name: 'ingested_at')
    /// The timestamp when the snapshot was ingested into the database.
    required DateTime ingestedAt,
    @JsonKey(name: 'battery_soc_percent')
    /// The state of charge of the battery in percentage (0-1).
    required double batteryStateOfCharge,
    @JsonKey(name: 'battery_voltage_v')
    /// The voltage of the battery in volts (V).
    required double batteryVoltage,

    @JsonKey(name: 'battery_current_a')
    /// The current of the battery in amperes (A).
    required double batteryCurrent,

    @JsonKey(name: 'battery_charge_power_w')
    /// The power of the battery in watts (W).
    required double chargePower,
    @JsonKey(name: 'battery_discharge_power_w')
    /// The power of the battery in watts (W).
    required double dischargePower,
    @JsonKey(name: 'battery_charge_energy_today_kwh')
    /// The energy charged into the battery today in kilowatt-hours (kWh).
    required double chargeEnergyToday,
    @JsonKey(name: 'battery_discharge_energy_today_kwh')
    /// The energy discharged from the battery today in kilowatt-hours (kWh).
    required double dischargeEnergyToday,
    @JsonKey(name: 'grid_active_power_w')
    /// The power from the grid in watts (W).
    required double gridActivePower,
    @JsonKey(name: 'grid_frequency_hz')
    /// The frequency of the grid in hertz (Hz).
    required double gridFrequency,
    @JsonKey(name: 'grid_voltage_v')
    /// The voltage of the grid in volts (V).
    required double gridVoltage,
    @JsonKey(name: 'grid_current_a')
    /// The current from the grid in amperes (A).
    required double gridCurrent,

    @JsonKey(name: 'grid_export_power_w')
    /// The power exported to the grid in watts (W).
    required double gridExportPower,

    @JsonKey(name: 'grid_export_energy_today_kwh')
    /// The total power exported from the grid today in kilowatt-hours (kWh).
    required double gridExportEnergyToday,

    @JsonKey(name: 'grid_import_energy_today_kwh')
    /// The total power imported from the grid today in kilowatt-hours (kWh).
    required double gridImportEnergyToday,
    @JsonKey(name: 'grid_charge_power_w')
    /// Unknown field related to grid power.
    required double gridChargePower,
    @JsonKey(name: 'solar_energy_today_kwh')
    /// The energy generated by the solar panels in watts (W).
    required double solarEnergyToday,
    @JsonKey(name: 'solar_power_w')
    /// The current power generated by the solar panels in kilowatt-hours (kWh).
    required double solarPower,
    @JsonKey(name: 'home_load_power_w')
    /// The current power consumed by the home in kilowatt-hours (kWh).
    required double homeLoadPower,
  }) = _InverterSnapshot;

  factory InverterSnapshot.fromJson(Map<String, dynamic> json) =>
      _$InverterSnapshotFromJson(json);
}
